//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationValidation.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class tbl_user
    {
        public int User_id { get; set; }
        [Display(Name = "Name")]
        [Required(ErrorMessage = "*")]
        [MaxLength(25,ErrorMessage = "Name cannot be longer than 25 characters.")]
       
        public string User_Name { get; set; }
        [Display(Name = "Address")]
        [Required(ErrorMessage = "*")]
        public string User_Address { get; set; }
        [Display(Name = "Email")]
        [Required(ErrorMessage = "*")]
        [DataType(DataType.EmailAddress)]
        [RegularExpression(@"^\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$", ErrorMessage = "Email is not valid.")]
        public string User_Email { get; set; }
        [Display(Name = "Birth Date")]
        [Required(ErrorMessage = "Birth Date is required.")]
        //[RegularExpression(@"(((0|1)[0-9]|2[0-9]|3[0-1])\/(0[1-9]|1[0-2])\/((19|20)\d\d))$", ErrorMessage = "Invalid date format.")]
        [Custom]
        public string User_birthday { get; set; }
        [Display(Name = "Gender")]
        [Required(ErrorMessage = "*")]
        public string User_Gender { get; set; }
        [Display(Name = "Password")]
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "*")]
        public string password { get; set; }
        [Display(Name = "Contact")]
        [Required(ErrorMessage = "*")]
        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"^([0-9]{10})$", ErrorMessage = "Please Enter Valid Mobile Number.")]
        public string User_mobile { get; set; }
    }
}
